---
- hosts: all
  sudo: yes

  vars:
  - warName: spring-boot-package-war-{{ Version }}.war
  - warRemotePath: /opt/tomcat/webapps/

  tasks:
  - name: ensure tomcat directory exists
    file:
      path: /opt/tomcat/webapps/spring-boot-package-war-{{ Version }}
      state: directory
  - name: Ansible copy war to remote server
    copy:
      src: target/{{ warName }}
      dest: "{{ warRemotePath }}"
  - name: ensure tomcat directory exists
    file:
      path: /opt/tomcat/webapps/spring-boot-package-war-{{ Version }}
      state: directory
  - name: Unzip WAR file
    unarchive:
                src={{ warRemotePath }}/{{ warName }} dest=/opt/tomcat/webapps/spring-boot-package-war-{{ Version }}
                copy=no mode=0755
                owner=tomcat group=tomcat
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent
  - name: Restart tomcat
    service: name=tomcat
             state=restarted
